apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronbackup
spec:
  schedule: "*/2 * * * *"  # Run every 2 mins
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronbackup
            image: aishwarya166/cc_cronbackup_image:latest
            #command: ["sh", "-c", "/usr/src/backup/entrypoint.sh"]
            #command: ["python3", "/usr/src/backup/main.py"]
            imagePullPolicy: Always
            volumeMounts:
            - name: backup-volume
              mountPath: /home/aishwarya/CC_027_052_062_739/backup/backupfiles
          restartPolicy: OnFailure
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: cronbackup-pvc

