apiVersion: v1
kind: PersistentVolume
metadata:
  name: cronbackup-pv
spec:
  capacity:
    storage: 1Gi  
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /home/aishwarya/CC_027_052_062_739/backup/backupfiles

