apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cronbackup-pvc
spec:
  volumeName: cronbackup-pv
  volumeMode: Filesystem
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  

