apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc-2
spec:
  volumeName: backup-pv-2
  volumeMode: Filesystem
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust this to match your PV size

