apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-2
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /Learning_pvc_pv/pv-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - worker02.kubernetes.com
